apiVersion: v1
kind: Service
metadata:
  name: intranet-portal-service
  labels:
    app: intranet-portal
spec:
  type: NodePort
  selector:
    app: intranet-portal
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
